module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                'assets':'@/assets',
                'components':'@/components',
                'router':'@/router',
                'assets':'@/assets',
                'network':'@/network'
            }
        }
    }
}